apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::240012938474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-74MBYX2FS50J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::240012938474:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-03T06:11:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1767"
  uid: 504c9004-db7e-42bf-a3fd-4165fb544ad2
